// Code generated by "stringer -type=Model"; DO NOT EDIT.

package sen6x

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SEN62-0]
	_ = x[SEN63C-1]
	_ = x[SEN65-2]
	_ = x[SEN66-3]
	_ = x[SEN68-4]
	_ = x[SEN69C-5]
}

const _Model_name = "SEN62SEN63CSEN65SEN66SEN68SEN69C"

var _Model_index = [...]uint8{0, 5, 11, 16, 21, 26, 32}

func (i Model) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Model_index)-1 {
		return "Model(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Model_name[_Model_index[idx]:_Model_index[idx+1]]
}
